before refactor

diff --git a/libexec/enve/base b/libexec/enve/base
--- a/libexec/enve/base
+++ b/libexec/enve/base
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 if [ -n "${HAVE_ENVE_BASE:-}" ]; then
     return 0
 fi
@@ -9,7 +8,7 @@ HAVE_ENVE_BASE=1
 ENVE_PROGRAM_NAME="${0##*/}"
 
 hascmd() {
-    command -v $1 >/dev/null
+    command -v "$1" >/dev/null
 }
 
 
@@ -26,8 +25,9 @@ if ! hascmd tac; then
     }
 fi
 
+
 in_busybox_shell() {
-    [ "$(ps -o pid,comm | awk '$1=='"$$"'{ print $2 }' | tail -n 1)" = "busybox" ]
+    [ "$SHELL" = "/bin/ash" ] && [ "$(ps -o pid,comm | awk '$1=='"$$"'{ print $2 }' | tail -n 1)" = "busybox" ]
 }
 
 if in_busybox_shell; then
@@ -35,34 +35,83 @@ if in_busybox_shell; then
     :
 fi
 
-hashstr() {
-    data="$(cat)"
-    echo "$data" | md5sum | while read -r sha __file; do
-        echo "$sha"
+replace() {
+    # c=0
+    while [ "$s" != "${s%%$1*}" ]; do
+        s="${s%%$1*}$2${s#*$1}"
+        # echo x "$s" "${s%%$1*}" >&2
+        # if [ "$c" -gt 100 ]; then
+        #     break
+        # fi
+        # c=$((c+1))
     done
+    # printf %s "$s"
+}
+
+hashstr() {
+    # data="$(cat)"
+    # echo "$data" | md5sum "$@" | while read -r sha __file; do
+    # shellcheck disable=2034
+    # md5sum "$@" | while read -r hashvalue __file; do
+
+    result=$(md5sum "$@")
+    hashvalue=
+    while read -r _hashvalue __file; do
+        hashvalue=${_hashvalue}
+        echo "$hashvalue"
+
+    done <<EOF
+$result
+EOF
+    __file=${__file}
+    unset _hashvalue __file
+}
+
+
+fast_readtext() {
+    text=
+    while IFS='' read -r line; do
+        text="$text${text:+$newl}$line"
+    done < "$1"
+    unset line
+}
+
+fast_dirname() {
+    d=${d%%/}
+    if [ -z "$d" ]; then
+        d=\.
+    elif [ -z "${d%/*}" ]; then
+        d=/
+    elif [ "$d" = "${d%/*}" ]; then
+        d=\.
+    else
+        d=${d%/*}
+    fi
 }
 
 combine_umask() {
+    mask=
     eval "mask=$((0$(umask) & 0$1))"
-    printf %o\\n $mask
+    printf %o\\n "$mask"
 }
 
 create_file_mutex() {
     (
-        umask $(combine_umask "${2:-7077}")
+        umask "$(combine_umask "${2:-7077}")"
         set -o noclobber
-        { > "$1" ; } &> /dev/null
+        { true > "$1" ; } >/dev/null 2>&1
     )
 }
 
 create_dir_mutex() {
     (
-        umask $(combine_umask "${2:-7077}")
-        mkdir "$1" &> /dev/null
+        umask "$(combine_umask "${2:-7077}")"
+        mkdir "$1" >/dev/null 2>&1
     )
 }
 
 _sixrand50() {
+    # shellcheck disable=1004
     awk 'BEGIN {  srand(); for (i = 1; i <= 50; i++)
                         printf("%c%c%c%c%c%c\n", rand() * 26 + 97, rand() * 26 + 97 \
                                                , rand() * 26 + 97, rand() * 26 + 97 \
@@ -101,8 +150,9 @@ mkdtemp() {
 # enve is a stateless program, that is unnecessary to use '/var'
 
 get_cachedir() {
-    if [ -n "$ENVE_CACHE_DIR" ]; then
+    if [ -n "${ENVE_CACHE_DIR:-}" ]; then
         echo "$ENVE_CACHE_DIR"
+        return 0
     fi
     kernal_name="$(uname -s)"
     case "$kernal_name" in
@@ -111,13 +161,15 @@ get_cachedir() {
                 # $HOME always contain only alphanum without space and all lowercase.
                 
                 # echo ~/Library/Caches/enve
+
+                # shellcheck disable=2034
                 read -r fileperm x2 fileuser x4 x5 x6 x7 x8 path <<EOF
-$(ls -ld /var/cache/enve)
+$(ls -ld /var/cache/enve 2>/dev/null)
 EOF
                 if [ "$fileperm" = "drwxrwxrwt" ] && [ "$fileuser" = "root" ]; then
                     echo /var/cache/enve
                 else
-                    echo ~/.cache/enve    
+                    echo ~/.cache/enve
                 fi
                 
             ;;
@@ -133,7 +185,9 @@ EOF
                 # but $HOME may contain non-acsii character or space.
                 # so, we use $ProgramData
                 # The file system directory that contains application data for all users.
-                echo "$(cygpath -u "$ProgramData/enve")"
+
+                # shellcheck disable=2154
+                cygpath -u "$ProgramData/enve"
             ;;
         *)
                 echo /var/cache/enve
@@ -143,13 +197,13 @@ EOF
 
 get_tempdir() {
     if [ -n "${TMP:-}" ]; then
-        echo "$TMP"
+        echo "${TMP%%/}"
     elif [ -n "${TMPDIR:-}" ]; then
-        echo "$TMPDIR"
+        echo "${TMPDIR%%/}"
     elif [ -n "${TEMP:-}" ]; then
-        echo "$TEMP"
+        echo "${TEMP%%/}"
     elif [ -n "${TEMPDIR:-}" ]; then
-        echo "$TEMPDIR"
+        echo "${TEMPDIR%%/}"
     else
         echo "/tmp"
     fi
@@ -169,21 +223,39 @@ save () {
 
 
 _loglevel_form_symbol() {
-    case ${ENVE_VERBOSE:-NOTICE} in
-        CRIT|CRITICAL)  echo "6" ;;
-        ERROR)          echo "5" ;;
-        WARN|WARNING)   echo "4" ;;
-        NOTICE)         echo "3" ;;
-        INFO)           echo "2" ;;
-        DEBUG)          echo "1" ;;
-        TRACE)          echo "0" ;;
+    case ${ENVE_VERBOSE:-TRACE} in
+        CRIT|CRITICAL)  loglevel=6 ;;
+        ERROR)          loglevel=5 ;;
+        WARN|WARNING)   loglevel=4 ;;
+        NOTICE)         loglevel=3 ;;
+        INFO)           loglevel=2 ;;
+        DEBUG)          loglevel=1 ;;
+        TRACE)          loglevel=0 ;;
 
-        *)              echo "3" ;;
+        *)              loglevel=3 ;;
     esac
+    if [ "${1:-nonfast}" = "nonfast" ]; then
+        echo "$loglevel"
+    fi
 }
 
 timestamp() {
-  date +%s%N | cut -b5-13
+    # date +%s%N | cut -b5-13
+    tm=$(date +%s%N)
+    # tm=$(/nix/store/p0zfmny1vsb4ryzn67p4rbm0nqk78yya-boot-env/bin/date +%s%N)
+    tm=${tm#?????}
+    tm=${tm%${tm#????????}}
+    echo "$tm"
+    unset tm
+}
+
+timestamp2() {
+    tm=$(date +%s%N)
+    # tm=$(/nix/store/p0zfmny1vsb4ryzn67p4rbm0nqk78yya-boot-env/bin/date +%s%N)
+    tm=${tm#?????}
+    tm=${tm%${tm#????????}}
+    echo "$tm"
+    unset tm
 }
 
 
@@ -197,14 +269,15 @@ _format_head() {
         case $1 in
             critical|error) C2="$Cr" ;;
         esac
+
         case ${ENVE_VERBOSE:-TRACE} in
             CRIT|CRITICAL)  fmts="$C1%4s$C0 $C2%8s$C0" ;;
             ERROR)          fmts="$C1%4s$C0 $C2%8s$C0" ;;
             WARN|WARNING)   fmts="$C1%4s$C0 $C2%8s$C0" ;;
             NOTICE)         fmts="$C1%4s$C0 $C2%8s$C0" ;;
             INFO)           fmts="$C1%4s$C0 $C2%8s$C0" ;;
-            DEBUG)          fmts="[$(date -u +"%D %T")] $C1%4s$C0 $C2%8s$C0" ;;
-            TRACE)          fmts="[$(timestamp)] $C1%4s$C0 $C2%8s$C0" ;;
+            DEBUG)          eval "fmts=\"[$(date -u +"%D %T")] $C1%4s$C0 $C2%8s$C0\"" ;;
+            TRACE)          eval "fmts=\"[$(timestamp)] $C1%4s$C0 $C2%8s$C0\"" ;;
         esac
     else
         case ${ENVE_VERBOSE:-NOTICE} in
@@ -213,57 +286,79 @@ _format_head() {
             WARN|WARNING)   fmts="%4s %s:" ;;
             NOTICE)         fmts="%4s %s:" ;;
             INFO)           fmts="%4s %8s:" ;;
-            DEBUG)          fmts="[$(date -u +"%D %T")] %4s %8s:" ;;
-            TRACE)          fmts="[$(timestamp)] %4s %8s:" ;;
+            DEBUG)          eval fmts=\""[$(date -u +"%D %T")] %4s %8s:"\" ;;
+            TRACE)          eval fmts=\""[$(timestamp)] %4s %8s:"\" ;;
         esac
     fi
+    # shellcheck disable=2059
     printf "$fmts" "$ENVE_PROGRAM_NAME" "$1"
 }
 
 critical() {
-    if [ $(_loglevel_form_symbol) -ge 6 ]; then
-        echo "$(_format_head ${LOGTYPE:-critical}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 6 ]; then
+        _format_head "${LOGTYPE:-critical}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-critical}) $*" >&2
     fi
 }
 error() {
-    if [ $(_loglevel_form_symbol) -ge 5 ]; then
-        echo "$(_format_head ${LOGTYPE:-error}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 5 ]; then
+        _format_head "${LOGTYPE:-error}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-error}) $*" >&2
     fi
 }
 
 warning() {
-    if [ $(_loglevel_form_symbol) -ge 4 ]; then
-        echo "$(_format_head ${LOGTYPE:-warning}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 4 ]; then
+        _format_head "${LOGTYPE:-warning}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-warning}) $*" >&2
     fi
 }
 
 notice() {
-    if [ $(_loglevel_form_symbol) -ge 3 ]; then
-        echo "$(_format_head ${LOGTYPE:-notice}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 3 ]; then
+        _format_head "${LOGTYPE:-notice}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-notice}) $*" >&2
     fi
 }
 
 # log() {
-#     if [ $(_loglevel_form_symbol) -ge 3 ]; then
-#         echo "$(_format_head warning) $@" >&2
+#     if [ "$(_loglevel_form_symbol)" -le 3 ]; then
+#         echo "$(_format_head warning) $*" >&2
 #     fi
 # }
 
 info() {
-    if [ $(_loglevel_form_symbol) -ge 2 ]; then
-        echo "$(_format_head ${LOGTYPE:-info}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 2 ]; then
+        _format_head "${LOGTYPE:-info}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-info}) $*" >&2
     fi
 }
 
 debug() {
-    if [ $(_loglevel_form_symbol) -ge 1 ]; then
-        echo "$(_format_head ${LOGTYPE:-debug}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 1 ]; then
+        _format_head "${LOGTYPE:-debug}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-debug}) $*" >&2
     fi
 }
 
 trace() {
-    if [ $(_loglevel_form_symbol) -ge 0 ]; then
-        echo "$(_format_head ${LOGTYPE:-trace}) $@" >&2
+    _loglevel_form_symbol fast
+    if [ "$loglevel" -le 0 ]; then
+        _format_head "${LOGTYPE:-trace}" >&2
+        echo " $*" >&2
+        # echo "$(_format_head ${LOGTYPE:-trace}) $*" >&2
     fi
 }
 
@@ -276,7 +371,40 @@ _debug() { debug "$@"; }
 _trace() { trace "$@"; }
 
 die() {
-    error "$@"
-    exit 1
+    trap - EXIT
+    if [ -n "${1:-}" ]; then
+        _error "$1"
+    fi
+    exit "${2:-1}"
 }
+
+
+settrace() {
+    # trap '[ $? -eq 0 ] || echo err in $FUNCNAME in $BASH_SOURCE >&2' EXIT
+
+    trap '
+    retcode=$?
+    if [ "$retcode" -ne 0 ]; then
+        if [ -n "${FUNCNAME:-}" ]; then
+            _trace "Traceback:"
+            i=0
+            while [ -n "${FUNCNAME[$i]:-}" ]; do
+                _trace "  File $(basename "${BASH_SOURCE[$i]}"), in ${FUNCNAME[$i]}"
+                i=$(( i + 1 ))
+            done
+        fi
+        _error "Unexpected exit code $retcode"
+    fi
+    '"$(eval echo \$\*)" EXIT
+    retcode=
+    set -eu
+    if hascmd shopt; then
+        # for posix-sh compative in bash, need bash>=4.4
+        # shellcheck disable=2039
+        shopt -s inherit_errexit >/dev/null 2>&1 || true
+    fi
+}
+
+
+
 
diff --git a/libexec/enve/findutils b/libexec/enve/findutils
--- a/libexec/enve/findutils
+++ b/libexec/enve/findutils
@@ -7,33 +7,43 @@ fi
 HAVE_ENVE_FINDUTILS=1
 
 
-tab="$(printf '\tx')"
-tab="${tab%x}"
-feed="$(printf '\fx')"
-feed="${feed%x}"
-vtab="$(printf '\vx')"
-vtab="${vtab%x}"
+# tab="$(printf '\tx')"
+# tab="${tab%x}"
+# feed="$(printf '\fx')"
+# feed="${feed%x}"
+# vtab="$(printf '\vx')"
+# vtab="${vtab%x}"
 newl="$(printf '\nx')"
 newl="${newl%x}"
 
 
 
-fnmatch_pathname_transform() {
-    pat="$1"
-    pat="${pat//\/\*\*\//\/!!!!!\/}"
-    pat="${pat//\*\*\//!!!!!\/}"
-    pat="${pat//\/\*\*/\/!!!!!}"
-    if [ "$pat" != "${pat//\*\*/}" ]; then
-        return 1
-    fi
-    pat="${pat//\*/\+\(\[\!\/\]\)}"
-    pat="${pat//\?/\@\(\[\!\/\]\)}"
-    pat="${pat//!!!!!\//\@\(\+\(\?\)\/\|\)}"   # replace to @(+(?)/|)
-    pat="${pat//!!!!!/\*}"
+# fnmatch_pathname_transform() {
+#     pat="$1"
+#     pat="${pat//\/\*\*\//\/!!!!!\/}"
+#     pat="${pat//\*\*\//!!!!!\/}"
+#     pat="${pat//\/\*\*/\/!!!!!}"
+#     if [ "$pat" != "${pat//\*\*/}" ]; then
+#         return 1
+#     fi
+#     pat="${pat//\*/\+\(\[\!\/\]\)}"
+#     pat="${pat//\?/\@\(\[\!\/\]\)}"
+#     pat="${pat//!!!!!\//\@\(\+\(\?\)\/\|\)}"   # replace to @(+(?)/|)
+#     pat="${pat//!!!!!/\*}"
+#     printf %s\\n "$pat"
+# }
 
-    printf %s\\n "$pat"
+
+fnmatch_pathname_transform_ere() {
+    sed -E \
+        -e 's#([\[\]\(\)\{\}\.\^\$\+\|])#\\\1#g' \
+        -e 's#([^*]|^)\*([^*]|$)#\1[^/]+\2#g' \
+        -e 's#/\*\*(/?)#/.*\1#g' \
+        -e 's#\*\*/#(.+/|)#g' \
+        -e 's#\?#[^/]#g'
+
+    # -e 's#\*#[^/]+#g' \
 }
-
 
 # POSIX: 2.13.1 Patterns Matching a Single Character
 # http://pubs.opengroup.org/onlinepubs/009696899/utilities/xcu_chap02.html#tag_02_13_01
@@ -49,88 +59,179 @@ fnmatch_pathname () {
 }
 
 
-make_gitignore_filter() {
-    # implement gitignore format
-    # output '__gf' function code, '__gf' filter filename per line from stdin.
-    # https://git-scm.com/docs/gitignore
-    #
-    # NOTE: this function will not respect this rule
-    # `it would only find a match with a directory if the pattern ends with a slash ("/").`
-    #
+# make_gitignore_filter() {
+#     # implement gitignore format
+#     # output '__gf' function code, '__gf' filter filename per line from stdin.
+#     # https://git-scm.com/docs/gitignore
+#     #
+#     # NOTE: this function will not respect this rule
+#     # `it would only find a match with a directory if the pattern ends with a slash ("/").`
+#     #
 
-    echo 'function __gf() {'
-    echo '  paths="$(cat)"'
-    echo '  origin_paths="$paths"'
-    echo "$1" | while IFS="$newl" read -r line; do
-        # A line starting with # serves as a comment
-        [ -z "$line" ] || [ "${line:0:1}" = "#" ] && continue
-        # Trailing spaces are ignored unless they are quoted with backslash ("\").
-        line="${line%%+([!\\][[:space:]])}"
+#     echo 'function __gf() {'
+#     echo '  paths="$(cat)"'
+#     echo '  origin_paths="$paths"'
+#     echo "$1" | while IFS="$newl" read -r line; do
+#         # A line starting with # serves as a comment
+#         [ -z "$line" ] || [ "${line:0:1}" = "#" ] && continue
+#         # Trailing spaces are ignored unless they are quoted with backslash ("\").
+#         line="${line%%+([!\\][[:space:]])}"
 
-        if ! pat="$(fnmatch_pathname_transform "$line")"; then
-            return 1
-        fi
-        if [ "${pat:0:1}" = '!' ] && [ "${pat:0:2}" != '\!' ]; then
-            pat=${pat:1}
-            echo 'paths="$paths${paths:+$newl}$(echo "$origin_paths" | while IFS="$newl" read -r path; do'
-            echo '  case "$path" in '"$pat"') printf %s\\n "$path";; esac ;'
-            echo 'done)"'
-        else
-            echo 'paths="$(echo "$paths" | while IFS="$newl" read -r path; do'
-            echo '  case "$path" in '"$pat"') continue;; esac ; printf %s\\n "$path" ;'
-            echo 'done)"'
-        fi
-    done
-    echo 'echo "$paths"'
-    echo '}'
-}
+#         if ! pat="$(fnmatch_pathname_transform "$line")"; then
+#             return 1
+#         fi
+#         if [ "${pat:0:1}" = '!' ] && [ "${pat:0:2}" != '\!' ]; then
+#             pat=${pat:1}
+#             echo 'paths="$paths${paths:+$newl}$(echo "$origin_paths" | while IFS="$newl" read -r path; do'
+#             echo '  case "$path" in '"$pat"') printf %s\\n "$path";; esac ;'
+#             echo 'done)"'
+#         else
+#             echo 'paths="$(echo "$paths" | while IFS="$newl" read -r path; do'
+#             echo '  case "$path" in '"$pat"') continue;; esac ; printf %s\\n "$path" ;'
+#             echo 'done)"'
+#         fi
+#     done
+#     echo 'echo "$paths"'
+#     echo '}'
+# }
 
+
+
+# gitignore_filter() {
+#     # only support in bash,zsh,ksh
+#     (
+#         eval "$(make_gitignore_filter "$1")"
+#         shopt -s extglob
+#         __gf
+#     )
+# }
+
+# gitignore_filter_ere() {
 gitignore_filter() {
-    # only support in bash,zsh,ksh
-    (
-        eval "$(make_gitignore_filter "$1")"
-        shopt -s extglob
-        __gf
-    )
+    # echo $1 >&2
+    # echo $(echo "$1" | fnmatch_pathname_transform_ere) >&2
+    positive=
+    negative=
+    while read -r pat; do
+        [ -z "$pat" ] && continue
+        [ "${pat%${pat#?}}" = "#" ] && continue
+        if [ "${pat%${pat#?}}" = "!" ]; then
+            negative="$negative${pat#?}$newl"
+        else
+            positive="$positive$pat$newl"
+        fi
+    done <<EOF
+$1
+EOF
+    genre() {
+        while read -r ere; do
+            printf "%s '%s' " "-e" "^$ere\$"
+        done <<EOF
+$(echo "$1" | fnmatch_pathname_transform_ere)
+EOF
+    }
+    data=$(cat)
+    if [ -n "$positive" ]; then
+        positive_pass=$(
+            printf 'grep -E -v '
+            genre "$positive"
+        )
+        positive_fail=$(
+            printf 'grep -E '
+            genre "$positive"
+        )
+        # !!!! TODO: grep: empty (sub)expression
+        echo "positive_pass: $positive_pass" >&2
+        echo "positive_fail: $positive_fail" >&2
+        echo "$data" | eval "$positive_pass" || true
+        if [ -n "$negative" ]; then
+            negative_pass=$(
+                printf 'grep -E '
+                genre "$negative"
+            )
+            # echo "negative_pass: $negative_pass" >&2
+            fail=$(echo "$data" | eval "$positive_fail" || true)
+            echo "$fail" | eval "$negative_pass" || true
+        fi
+    else
+        echo "$data"
+    fi
 }
+
 
 _files_stats() {
     content="$1"
     shift
+    first=
     for path in "$@"; do
-        (
-            set -euo pipefail
-            dirn=
-            if [ -z "$path" ]; then
-                continue
-            elif [ -d "$path" ]; then
-                dirn="$path"
-                finded=.
-            elif [ "${path/\//}" = "$path" ]; then
-                # '$path' contain '/'
-                dirn="${path%/*}"
-                finded="${path##*/}"
-            else
-                # '$path' NOT contain '/'
-                dirn=
-                finded="$path"
-            fi
-            if [ -n "$dirn" ]; then
-                cd "$dirn" || continue
-            fi
-            if [ ! -e "$finded" ]; then
-                continue
-            fi
-            # find "$finded" \
-            #   \( ! -type d -printf "%y %m %U %G %s %TY/%Tm/%Td %TH:%TM:%TS %p\\n" \) -o \
-            #   \( -type d -printf "%y %m %U %G 0 %TY/%Tm/%Td %TH:%TM:%TS %p\\n" \)
-            LANG=C ls -ln $(find "$finded" ! -type d) | awk '!($2="")' 
-            if [ -n "$content" ]; then
-                md5sum $(find "$finded" -type f)
-            fi
-        )
+        dirn=
+        if [ -z "$first" ]; then
+            set --
+            first=1
+        fi
+        if [ -z "$path" ]; then
+            continue
+        elif [ ! -d "$path" ]; then
+            set -- "$@" "$path"
+            continue
+        else
+            dirn="$path"
+            finded=.
+        fi
+        # elif [ "${path/\//}" = "$path" ]; then
+        #     # '$path' contain '/'
+        #     dirn="${path%/*}"
+        #     finded="${path##*/}"
+        # else
+        #     # '$path' NOT contain '/'
+        #     dirn=
+        #     finded="$path"
+        # fi
+        if [ -n "$dirn" ]; then
+            cd "$dirn" || continue
+        fi
+        if [ ! -e "$finded" ]; then
+            continue
+        fi
+        # find "$finded" \
+        #   \( ! -type d -printf "%y %m %U %G %s %TY/%Tm/%Td %TH:%TM:%TS %p\\n" \) -o \
+        #   \( -type d -printf "%y %m %U %G 0 %TY/%Tm/%Td %TH:%TM:%TS %p\\n" \)
+
+        if [ "$content" != 'content-only' ]; then
+            # shellcheck disable=2012 disable=2046
+            # LANG=C ls -ln $(find "$finded" ! -type d) | awk '!($2="")'
+            
+            # shellcheck disable=2012 disable=2046
+            while read -r x1 hardlink x3 x4 x5 x6 x7 x8 path; do
+                echo "$x1 - $x3 $x4 $x5 $x6 $x7 $x8 $path"
+            done <<EOF
+$(LANG=C ls -ln $(find "$finded" ! -type d))
+EOF
+        fi
+        if [ -n "$content" ]; then
+            # shellcheck disable=2046
+            md5sum $(find "$finded" -type f)
+        fi
     done
+    if [ $# -gt 0 ]; then
+        if [ "$content" != 'content-only' ]; then
+            # shellcheck disable=2012
+            # LANG=C ls -ln "$@" | awk '!($2="")'
+            while read -r x1 hardlink x3 x4 x5 x6 x7 x8 path; do
+                echo "$x1 - $x3 $x4 $x5 $x6 $x7 $x8 $path"
+            done <<EOF
+$(LANG=C ls -ln "$@")
+EOF
+        fi
+        hardlink=$hardlink
+        unset x1 hardlink x3 x4 x5 x6 x7 x8 path
+
+        if [ -n "$content" ]; then
+            md5sum "$@"
+        fi
+    fi
 }
+
 
 files_stats() {
     _files_stats "" "$@"
@@ -138,4 +239,8 @@ files_stats() {
 
 files_stats_contents() {
     _files_stats "content" "$@"
+}
+
+files_contents() {
+    _files_stats "content-only" "$@"
 }
diff --git a/libexec/enve/isolation b/libexec/enve/isolation
--- a/libexec/enve/isolation
+++ b/libexec/enve/isolation
@@ -28,14 +28,25 @@ timestamp() {
 
 
 # echo "$(timestamp) start"
+# ENVE_HOME="$(dirname $0)"
+if [ -z "${ENVE_HOME:-}" ]; then
+    echo "fatal: ENVE_HOME not set." >&2
+    exit 1
+fi
 
-ENVE_HOME="$(dirname $0)"
-
+# shellcheck source=libexec/enve/envelib
 . "$ENVE_HOME/enve/base"
+# shellcheck source=libexec/enve/envelib
 . "$ENVE_HOME/enve/envelib"
 
 
 true "
+
+cygwin 有關於切換使用者的參考資料
+https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-setuid-overview
+cygstart --action=runas "\$@"
+
+
 # invoke 協定
 
 (O)path - chroot path
@@ -147,18 +158,20 @@ pm 只是單純的 event trigger
 "
 
 plain() {
-    local mesg=$1; shift
-    printf "    $mesg\n" "$@" >&1
+    mesg=$1; shift
+    # shellcheck disable=2059
+    printf "    $mesg\\n" "$@" >&1
 }
 
 quiet() {
     _optquiet=0
-    (( _optquiet )) || plain "$@"
+    [ "${_optquiet}" -ne 0 ] || plain "$@"
 }
 
 error() {
-    local mesg=$1; shift
-    printf "$==> ERROR: $mesg\n" "$@" >&2
+    mesg=$1; shift
+    # shellcheck disable=2059
+    printf "$==> ERROR: $mesg\\n" "$@" >&2
     return 1
 }
 
@@ -171,46 +184,51 @@ add_file() {
     #   $2: destination on initcpio (optional, defaults to same as source)
     #   $3: mode
 
-    (( $# )) || return 1
+    [ $# -ne 0 ] || return 1
 
     # determine source and destination
-    local src=$1 dest=${2:-$1} mode=
+    src=$1
+    dest=${2:-$1}
+    mode=
 
-    if [[ ! -f $src ]]; then
+    if [ ! -f "$src" ]; then
         error "file not found: \`%s'" "$src"
         return 1
     fi
 
     mode=${3:-$(stat -c %a "$src")}
-    if [[ -z $mode ]]; then
+    if [ -z "$mode" ]; then
         error "failed to stat file: \`%s'." "$src"
         return 1
     fi
 
-    if [[ -e $CHROOT/$dest ]]; then
+    if [ -e "$CHROOT/$dest" ]; then
         quiet "overwriting file: %s" "$dest"
     else
         quiet "adding file: %s" "$dest"
     fi
-    command install -Dm$mode "$src" "$CHROOT/$dest"
+    command install -Dm"$mode" "$src" "$CHROOT/$dest"
 }
 
+
 add_binary() {
+    # TODO: posix
+
     # Add a binary file to the initcpio image. library dependencies will
     # be discovered and added.
     #   $1: path to binary
     #   $2: destination on initcpio (optional, defaults to same as source)
 
     local -a sodeps
-    local line= regex= binary= dest= mode= sodep= resolved=
+    local line='' regex='' binary='' dest='' mode='' sodep='' resolved=''
 
-    if [[ ${1:0:1} != '/' ]]; then
+    if [ "${1%${1#?}}" != '/' ]; then
         binary=$(type -P "$1")
     else
         binary=$1
     fi
 
-    if [[ ! -f $binary ]]; then
+    if [ ! -f "$binary" ]; then
         error "file not found: \`%s'" "$1"
         return 1
     fi
@@ -245,7 +263,7 @@ add_binary() {
             # (( ++_builderrors ))
             continue
         fi
-        if [[ -f $sodep && ! -e $CHROOT/$sodep ]]; then
+        if [ -f "$sodep" ] && [ ! -e "$CHROOT/$sodep" ]; then
             case $(uname) in
                 Linux)
                         add_file "$sodep" "$sodep" "$(stat -Lc %a "$sodep")"
@@ -255,8 +273,9 @@ add_binary() {
                     ;;
             esac
         fi
-    done <<< "$lddout"
-
+    done <<EOF
+$lddout
+EOF
     return 0
 }
 
@@ -267,14 +286,14 @@ simple_root_mac() {
 
     # setup root filesystem
     for d in bin boot dev etc home lib share usr var opt run; do
-        install -d -m755 $d
+        install -d -m755 "$d"
     done
     install -d -m0750 root
     install -d -m1777 tmp
 
     # setup /var
     for d in cache local opt log/old lib/misc empty; do
-        install -d -m755 var/$d
+        install -d -m755 "var/$d"
     done
     install -d -m1777 var/tmp
 
@@ -283,10 +302,10 @@ simple_root_mac() {
 
     # setup /usr hierarchy
     for d in bin include lib share/misc src; do
-        install -d -m755 usr/$d
+        install -d -m755 "usr/$d"
     done
-    for d in {1..8}; do
-        install -d -m755 usr/share/man/man$d
+    for d in 1 2 3 4 5 6 7 8; do
+        install -d -m755 "usr/share/man/man$d"
     done
 
     cd -
@@ -297,12 +316,14 @@ simple_root_mac() {
     for name in fd/1 fd/2 stdin stdout stderr; do
         cp -a "/dev/$name" "$CHROOT/dev"
     done
-    for name in tty ttyp{1,2,3,4,5,6}; do
-        cp -a /dev/${name} "$CHROOT/dev"
+    for d in 1 2 3 4 5 6; do
+        cp -a "/dev/ttyp$d" "$CHROOT/dev"
     done
+    cp -a "/dev/tty" "$CHROOT/dev"
+
 
     # certs
-    cp -a /etc/ssl $CHROOT/etc/ssl
+    cp -a /etc/ssl "$CHROOT/etc/ssl"
     
     add_binary /bin/bash
     add_binary /bin/sh
@@ -322,7 +343,7 @@ simple_root() {
 
     # setup root filesystem
     for d in bin boot dev etc home lib share usr var opt run; do
-        install -d -m755 $d
+        install -d -m755 "$d"
     done
     install -d -m555 proc
     install -d -m555 sys
@@ -330,20 +351,20 @@ simple_root() {
     install -d -m1777 tmp
 
     # setup /etc and /usr/share/factory/etc
-    for file in group host.conf hosts issue motd nsswitch.conf \
-           passwd resolv.conf securetty shells profile; do
-        echo "$(eval echo "\"\$$(normalize ${file})_source\"")" > etc/$file
-        chmod 644 etc/$f
-    done
-    for file in gshadow shadow; do
-        echo "$(eval echo "\"\$$(normalize ${file})_source\"")" > etc/$file
-        chmod 600 etc/$file
-    done
+    # for file in group host.conf hosts issue motd nsswitch.conf \
+    #        passwd resolv.conf securetty shells profile; do
+    #     echo "$(eval echo "\"\$$(normalize "${file}")_source\"")" > etc/$file
+    #     chmod 644 etc/$f
+    # done
+    # for file in gshadow shadow; do
+    #     echo "$(eval echo "\"\$$(normalize "${file}")_source\"")" > etc/$file
+    #     chmod 600 "etc/$file"
+    # done
     ln -s ../proc/self/mounts etc/mtab
 
     # setup /var
     for d in cache local opt log/old lib/misc empty; do
-        install -d -m755 var/$d
+        install -d -m755 "var/$d"
     done
     install -d -m1777 var/tmp
 
@@ -352,28 +373,30 @@ simple_root() {
 
     # setup /usr hierarchy
     for d in bin include lib share/misc src; do
-        install -d -m755 usr/$d
+        install -d -m755 "usr/$d"
     done
-    for d in {1..8}; do
-        install -d -m755 usr/share/man/man$d
+    for d in 1 2 3 4 5 6 7 8; do
+        install -d -m755 "usr/share/man/man$d"
     done
 
     cd -
 
 
     for name in null zero full random urandom kmsg tty ptmx fuse; do
-        cp -a /dev/$name "$CHROOT/dev"
+        cp -a "/dev/$name" "$CHROOT/dev"
     done
     for name in fd stdin stdout stderr; do
-        cp -a /dev/$name "$CHROOT/dev"
+        cp -a "/dev/$name" "$CHROOT/dev"
     done
     for name in tty vcs vcsa; do
-        cp -a /dev/${name}{1,2,3,4,5,6} "$CHROOT/dev"
+        for d in 1 2 3 4 5 6; do
+            cp -a "/dev/${name}$d" "$CHROOT/dev"
+        done
     done
 
     mkdir "$CHROOT/etc/pam.d"
     for file in /etc/pam.d/*; do
-        cp -a $file "$CHROOT/$file"
+        cp -a "$file" "$CHROOT/$file"
     done
 
     # chroot_add_mount proc "$CHROOT/proc" -t proc -o nosuid,noexec,nodev
@@ -394,7 +417,7 @@ simple_root() {
 
     # TODO: nix
     # certs
-    cp -a /etc/ssl $CHROOT/etc/ssl
+    cp -a /etc/ssl "$CHROOT/etc/ssl"
 
     # chroot_add_mount /bin "$1/bin" --bind -o ro
     # chroot_add_mount /lib "$1/lib" --bind -o ro
@@ -423,16 +446,17 @@ degrade
 3. leave /bin/tini, this will umount inner root
 4. stop root.service, this will umount outer root, and delete root
 "
+x=$x
 
 
 _exitrootdir() {
     if [ -n "${sleeppid:-}" ]; then
-        kill -SIGTERM $sleeppid
-        if mount | cut -f3 -d" " | grep $CHROOT; then
-            mount | cut -f3 -d" " | grep $CHROOT | sort -r | xargs umount || true
+        kill -SIGTERM "$sleeppid"
+        if mount | cut -f3 -d" " | grep "$CHROOT"; then
+            mount | cut -f3 -d" " | grep "$CHROOT" | sort -r | xargs umount || true
         fi
-        if ! mount | cut -f3 -d" " | grep $CHROOT; then
-            rm -rf $CHROOT
+        if ! mount | cut -f3 -d" " | grep "$CHROOT"; then
+            rm -rf "$CHROOT"
         else
             error "umount recursive fail, $CHROOT is not removed."
         fi
@@ -443,16 +467,16 @@ _exitrootdir() {
 }
 
 mkchroot() {
-    mkdir -p $CHROOT
+    mkdir -p "$CHROOT"
     if [ -n "${CHROOT_TEMPLATE:-}" ]; then
-        cp -a $CHROOT_TEMPLATE/* $CHROOT
+        cp -a "$CHROOT_TEMPLATE"/* "$CHROOT"
     fi
     case $(uname) in
         Linux)      simple_root;;
         Darwin)     simple_root_mac;;
     esac
     for bin in ${CHROOT_BINS:-}; do
-        add_binary $bin
+        add_binary "$bin"
     done
 }
 
@@ -478,7 +502,7 @@ delayinit() {
 
     # echo delayinit
     pid="$1"
-    while read pmpid; do
+    while read -r pmpid; do
         pipepid=$pmpid
     done < "$OUTER_PIPE"
     if [ "$pid" != "$pipepid" ]; then
@@ -491,10 +515,10 @@ delayinit() {
     case $uname_cached in
         Linux)
             if [ -n "${JAIL:-}" ]; then
-                printf "0:0:10000\n" > /etc/subuid
-                printf "0:0:10000\n" > /etc/subgid
-                newuidmap $pid 0 0 1  1 3001 3000 || echo "newuidmap $pid faild"
-                newgidmap $pid 0 0 1  1 3001 3000 || echo "newgidmap $pid faild"
+                printf "0:0:10000\\n" > /etc/subuid
+                printf "0:0:10000\\n" > /etc/subgid
+                newuidmap "$pid" 0 0 1  1 3001 3000 || echo "newuidmap $pid faild"
+                newgidmap "$pid" 0 0 1  1 3001 3000 || echo "newgidmap $pid faild"
                 # MOUNT_CMD="enter $pid mount"
             fi
             ;;
@@ -502,7 +526,7 @@ delayinit() {
 
     # mount
     while read -r src mount_point fstype option; do
-        $MOUNT_CMD -o $option -t $fstype $src $mount_point
+        $MOUNT_CMD -o "$option" -t "$fstype" "$src" "$mount_point"
     done < /dev/null
 
     # rm "$OUTER_PIPE"
@@ -525,7 +549,7 @@ dosuspend() {
     echo $$ > "$PIPE_PATH"
     count=0
     while [ -e "$PIPE_PATH" ]; do
-        count=$(($count + 1))
+        count=$((count + 1))
         if [ $count -gt $timeout_sec ]; then
             return 1
         fi
@@ -550,7 +574,7 @@ install_launcher() {
         INNER_SCRIPT=$LAUNCHER_ROOT/launcher
     fi
     mkfifo -m 600 "$OUTER_PIPE"
-    chown ${EXEC_USER:-$USER}  "$OUTER_PIPE"
+    chown "${EXEC_USER:-$USER}" "$OUTER_PIPE"
 
     # exec.cwd
     # exec.umask
@@ -614,22 +638,27 @@ _redirect_stdio() {
 
 
 start_with_namespace() {
-    user=${EXEC_USER:-nobody}
+    
 
     # exec unshare --ipc --uts --cgroup --net --user --pid --mount \
     #     chroot --userspec=$user:$user "$CHROOT" /bin/sh "$INNER_SCRIPT" $EXEC_START $(_stdio_txt)
     # (
         hascmd setsid && setsid
         _redirect_stdio
-        exec unshare --ipc --uts --cgroup --net --user --pid --mount \
-            chroot --userspec=$user:$user "$CHROOT" /bin/sh "$INNER_SCRIPT" $EXEC_START &
+
+        # exec unshare --ipc --uts --cgroup --net --user --pid --mount \
+        #     chroot --userspec=$user:$user "$CHROOT" /bin/sh "$INNER_SCRIPT" $EXEC_START &
+        user=${EXEC_USER:-nobody} \
+        INNER_SCRIPT=$INNER_SCRIPT \
+            eval exec unshare --ipc --uts --cgroup --net --user --pid --mount \
+            chroot --userspec=\$user:\$user \"\$CHROOT\" /bin/sh \"\$INNER_SCRIPT\" "$EXEC_START" &
         # [ -n "${WRITE_PIDFILE:-}" ] && echo $! > $PIDFILE
         PID=$!
     # ) &
 }
 
 start_with_chroot() {
-    user=${EXEC_USER:-nobody}
+    
     
     # sh -c '(exec chroot --userspec='$user:$user' "'"$CHROOT"'" \
     #         /bin/sh "'"$INNER_SCRIPT"'" '"$EXEC_START $(_stdio_txt)"' &
@@ -637,7 +666,11 @@ start_with_chroot() {
     # (
         hascmd setsid && setsid
         _redirect_stdio
-        exec chroot --userspec=$user:$user "$CHROOT" /bin/sh "$INNER_SCRIPT" $EXEC_START &
+
+        # exec chroot --userspec=$user:$user "$CHROOT" /bin/sh "$INNER_SCRIPT" $EXEC_START &
+        user=${EXEC_USER:-nobody} \
+        INNER_SCRIPT=$INNER_SCRIPT \
+            eval exec chroot --userspec=\$user:\$user \"\$CHROOT\" /bin/sh \"\$INNER_SCRIPT\" "$EXEC_START" &
         # [ -n "${WRITE_PIDFILE:-}" ] && echo $! > $PIDFILE
         PID=$!
     # ) &
@@ -645,7 +678,7 @@ start_with_chroot() {
 }
 
 start_switch_user() {
-    user=${EXEC_USER:-nobody}
+    
 
     # (
         hascmd setsid && setsid
@@ -653,7 +686,11 @@ start_switch_user() {
         # echo su - -m $user "$INNER_SCRIPT" $EXEC_START 
         # exec su - -m $user "$INNER_SCRIPT" $EXEC_START &
         # exec sudo -u $user /bin/sh "$INNER_SCRIPT" $EXEC_START &
-        exec chroot --userspec=$user:$user "/" /bin/sh "$INNER_SCRIPT" $EXEC_START &
+
+        # exec chroot --userspec=$user:$user "/" /bin/sh "$INNER_SCRIPT" $EXEC_START &
+        user=${EXEC_USER:-nobody} \
+        INNER_SCRIPT=$INNER_SCRIPT \
+            eval exec chroot --userspec=\$user:\$user / /bin/sh \"\$INNER_SCRIPT\" "$EXEC_START" &
         # [ -n "${WRITE_PIDFILE:-}" ] && echo $! > $PIDFILE
         PID=$!
     # ) &
@@ -662,7 +699,9 @@ start_switch_user() {
 start_normal() {
     hascmd setsid && setsid
     _redirect_stdio
-    exec /bin/sh "$INNER_SCRIPT" $EXEC_START
+    # exec /bin/sh "$INNER_SCRIPT" $EXEC_START
+    INNER_SCRIPT=$INNER_SCRIPT \
+        eval exec /bin/sh \"\$INNER_SCRIPT\" "$EXEC_START"
 }
 
 start_common() {
@@ -708,7 +747,7 @@ launch_subprocess() {
     if delayinit "$PID"; then
         rm -rf "${PIDFILE%/*}"
     else
-        kill -9 $pipepid
+        kill -9 "$pipepid"
         rm -rf "${PIDFILE%/*}"
         return 1
     fi
@@ -755,11 +794,12 @@ startns() {
 }
 
 selfhost() {
-    contname="$(basename $1)"
+    contname="$(basename "$1")"
     CHROOT=/var/cont/$contname/root
 
     serverootdir &
     servepid=$!
+    # shellcheck disable=2064
     trap "kill -SIGTERM $servepid" EXIT
     sleep 5
     startns
diff --git a/libexec/enve/pathutils b/libexec/enve/pathutils
--- a/libexec/enve/pathutils
+++ b/libexec/enve/pathutils
@@ -10,6 +10,7 @@ HAVE_ENVE_PATHUTILS=1
 readlink_posix() {
     # readlink '.' or '..' always return 1
     (
+        # shellcheck disable=2012 disable=2010
         if ! links="$(ls -ld "$@" | grep " -> ")"; then
             return 1
         else
@@ -21,10 +22,10 @@ readlink_posix() {
 ensure_readlink_command() {
     if [ -n "${ENVE_READLINK:-}" ]; then
         return 0
-    elif command -v 'greadlink' >/dev/null; then
-        ENVE_READLINK='greadlink'
     elif command -v 'readlink' >/dev/null; then
         ENVE_READLINK='readlink'
+    elif command -v 'greadlink' >/dev/null; then
+        ENVE_READLINK='greadlink'
     else
         ENVE_READLINK="readlink_posix"
     fi    
@@ -64,33 +65,34 @@ rsplit_path() {
     fi
 }
 
+_cd_target() {
+    split_path "$TARGET" || return 1
+    NAME="$basepath"
+    # cd "${dirpath:-/}" 2>/dev/null || return 1
+    cd "${dirpath:-/}" || return 1
+}
 
 resolve_symlinks() {
     # If $1 is a symlink, follow it as many times as possible, return absolute path
 
     ensure_readlink_command
-
-    cd_target() {
-        split_path "$TARGET" || return 1
-        NAME="$basepath"
-        # cd "${dirpath:-/}" 2>/dev/null || return 1
-        cd "${dirpath:-/}" || return 1
-    }
-
     (
         TARGET="$1"
-        cd_target || return 1
+        _cd_target || return 1
         # Iterate down a (possible) chain of symlinks
         while [ -L "$NAME" ]
         do
             TARGET="$($ENVE_READLINK "$NAME")" || return 1
-            cd_target || return 1
+            _cd_target || return 1
         done
 
         if [ "$NAME" = ".." ]; then
-            echo "$(cd "$(pwd -P)/.."; echo "$(pwd)")"
+            echo "$(cd "$(pwd -P)/.."; pwd)" || {
+                echo "cannot change directory" >&2
+                return 1
+            }
         elif [ "$NAME" = "." ]; then
-            echo "$(pwd -P)"
+            pwd -P
         else
             parent="$(pwd -P)"
             if [ "$parent" = "/" ]; then
@@ -103,15 +105,18 @@ resolve_symlinks() {
 }
 
 normalize() {
-    (
-        path="${1:-}"
+    # (
+        path=${1:-}
+        nonfast=${2:-nonfast}
         tailslash=
         if [ -n "$path" ] && [ -z "${path##*/}" ]; then
             tailslash=/
         fi
         set --
+        OLDIFS=$IFS
         IFS=/
         for c in $path; do
+            IFS=$OLDIFS
             case $c in
                 '')
                         if [ $# -eq 0 ]; then
@@ -159,40 +164,61 @@ normalize() {
         fi
 
         if [ $# -eq 0 ]; then
-            echo ""
+            ret=
         elif [ -z "$1" ] && [ $# -eq 1 ]; then
-            echo "/"
+            ret="/"
         else
-            output="$1"
+            ret="$1"
             shift
             for c; do
-                output="$c/$output"
+                ret="$c/$ret"
             done
-            echo "$output"
+            
         fi
-
-    )
+        if [ "$nonfast" = "nonfast" ]; then
+            echo "$ret"
+        fi
+    # )
 }
+
 
 follow_one() {
     # "$1" must be a absolute path,
     # and not contain any symlink componment except last componment
+    dst=$1
 
-    if [ -L "$1" ]; then
-        resolve_parts "$(normalize "$1/..")" "$($ENVE_READLINK "$1")"
+    if [ -L "$dst" ]; then
+        # resolve_parts "$(normalize "$dst/..")" "$($ENVE_READLINK "$dst")"
+        
+        # normalize "$dst/.." fast
+        dstdir=${dst%/*}
+        if [ -z "$dstdir" ]; then
+            dstdir=/
+        fi
+        resolve_parts "$dstdir" "$($ENVE_READLINK "$dst")" fast || {
+            return 1
+        }
     else
-        normalize "$1"
+        normalize "$dst" fast || {
+            return 1
+        }
+    fi
+    if [ "${2:-nonfast}" = "nonfast" ]; then
+        echo "$ret"
     fi
 }
 
-follow_directory() {
-    ret="$(follow_one "$1")"
+follow_directory_fast() {
+    # ret="$(follow_one "$1")"
+    follow_one "$1" fast || {
+        return 1
+    }
     # respect 'realpath' and 'readlink -f' behavier
     if [ ! -d "$ret" ]; then
         return 1
     fi
-    echo "$ret"
 }
+
 
 resolve_parts() {
     # resolve $2 (unknown) to $1 (known)
@@ -203,51 +229,69 @@ resolve_parts() {
     #  -> (resolve_parts "1/2/3/4" "5")
     #  -> "1/2/3/4/5"
     
-    if [ $infcnt -gt 100 ]; then
+    if [ "$infcnt" -gt 100 ]; then
         echo "too many chain of symlinks" >&2
         return 1
     fi
-    infcnt=$(($infcnt + 1))
+    infcnt=$((infcnt + 1))
 
     known="$1"
     unknown="$2"
+
+    # echo "resolve_parts:($known):($unknown)" >&2
+
     rsplit_path "$unknown" || return 1
-    
 
     if [ "$headpath" = "" ] && [ "$tailpath" = "" ]; then
         # unknown is root
-        echo "/"
-        return
+        ret="/"
     elif [ "$headpath" = "" ]; then
         # unknown is abspath
-        resolve_parts "/" "$tailpath"
-        return
-    fi
-
-    # resolve known part if that is not absolute path
-    if [ "${known%${known#?}}" != "/" ]; then
-        split_path "$known"
-        abs="$(cd "$dirpath"; pwd)"
-        known=$(resolve_parts "/" "$abs/$basepath")
-    elif [ "$known" = "/" ]; then
-        known=
-    fi
-
-    if [ "$tailpath" = "" ]; then
-        # unknown is the only last componment and user indicate that last componment is a directory
-        # example: this/must/be_dir/
-        follow_directory "$known/$headpath"
-    elif [ "$headpath" = "." ]; then
-        # unknown is the only last componment
-        follow_one "$known/$tailpath"
+        resolve_parts "/" "$tailpath" fast
     else
-        # unknown is a relative path contain more then two componments
-        new_known="$(follow_directory "$known/$headpath")" || return 1
-        resolve_parts "$new_known" "$tailpath"
+        # resolve known part if that is not absolute path
+        if [ "${known%${known#?}}" != "/" ]; then
+            split_path "$known"
+            abs="$(cd "$dirpath"; pwd)" || {
+                echo "cannot change directory" >&2
+                return 1
+            }
+            known=$(resolve_parts "/" "$abs/$basepath") || {
+                # echo "XXXX" >&2
+                return 1
+            }
+        elif [ "$known" = "/" ]; then
+            known=
+        fi
+
+        if [ "$tailpath" = "" ]; then
+            # unknown is the only last componment and user indicate that last componment is a directory
+            # example: this/must/be_dir/
+            follow_directory_fast "$known/$headpath" || return 1
+        elif [ "$headpath" = "." ]; then
+            # unknown is the only last componment
+            follow_one "$known/$tailpath" fast || return 1
+        else
+            # unknown is a relative path contain more then two componments
+            # new_known="$(follow_directory "$known/$headpath")" || return 1
+            set -- "$1" "$2" "${3:-}" "$tailpath"
+            follow_directory_fast "$known/$headpath" || {
+                return 1
+            }
+            new_known=$ret
+            tailpath=$4
+            resolve_parts "$new_known" "$tailpath" fast || {
+                return 1
+            }
+        fi
+    fi
+    if [ "${3:-nonfast}" = "nonfast" ]; then
+        echo "$ret"
     fi
 }
 
 canonicalize_symlinks() {
+
     # example: /a/b/../c
     #
     # 1. resolve as $(readlink /a/c)   
